blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/typedoc2md/typedoc-plugin-markdown/discussions/categories/q-a
    about: Ask a question on the discussions board.
