name: CI
on:
  push:
    paths:
      - 'packages/typedoc-plugin-markdown/**'
      - '!packages/typedoc-plugin-markdown/README.md'
      - '!packages/typedoc-plugin-markdown/CHANGELOG.md'
      - '!packages/typedoc-plugin-markdown/package.json'
  pull_request:
    paths:
      - 'packages/typedoc-plugin-markdown/**'
      - '!packages/typedoc-plugin-markdown/README.md'
      - '!packages/typedoc-plugin-markdown/CHANGELOG.md'
      - '!packages/typedoc-plugin-markdown/package.json'
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint --workspace typedoc-plugin-markdown
      - name: Build
        run: npm run build --workspaces --if-present
      - name: Test
        run: npm run test --workspaces --if-present
